### ISSUE TITLE
interObjectDelay not affecting Android 8+

### ISSUE THREAD

**Issue by idanatz** [willowtreeapps/spruce-android#108]
Hi, first of all, thanks for this great library, it's awesome!

I have encountered a problem with Android 8 devices where the interObjectDelay field is not affecting the items in recycler view.

For example:

`new Spruce.SpruceBuilder(mHashtagsRecyclerView)
                .sortWith(new LinearSort(100L, false, LinearSort.Direction.TOP_TO_BOTTOM))
                .animateWith(
                        DefaultAnimations.shrinkAnimator(mHashtagsRecyclerView, 400),
                        ObjectAnimator.ofFloat(mHashtagsRecyclerView, "translationX", -mHashtagsRecyclerView.getWidth(), 0f).setDuration(200)
                )`

This snippet works on pre Oreo devices perfectly but on 8 and above all the items appear at the same time without the 100ms delay.

**Moreover, the same happens in the example app you provide with this repo, so I guess this issue is affecting more users.**

Tested on Spruce version 1.0.1 with devices:
Galaxy s6 edge - Android 7.0 - working
Nexus 5x - Android 8.1 - not working
One Plus 5T - Android 8.1 - not working

**Comment by baselbj** [comment]
I am facing the same issue

**Comment by bret-fears** [comment]
Yes, @amooose added a fix for this in 8b457a3
