### ISSUE TITLE
Version 1.0.2 doesn't seem to work

### ISSUE THREAD

**Issue by amanzan** [willowtreeapps/spruce-android#120]
Added 
```
implementation 'com.willowtreeapps.spruce:spruce-android:1.0.2'
``` 

in my project's build.gradle, but then I try to setup the basic configuration like this:
```
        val spruceAnimator: Animator = SpruceBuilder(parentViewGroup)
                .sortWith(Default( /*interObjectDelay=*/50L))
                .animateWith(arrayOf<Animator>(DefaultAnimations.shrinkAnimator(parentViewGroup,  /*duration=*/800)))
                .start()
```

 and I get unresolved reference in SpruceBuilder, Default and DefaultAnimations

Trying to run my project, I get:
```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.willowtreeapps.spruce:spruce-android:1.0.2.
     Required by:
         project :app
      > Could not resolve com.willowtreeapps.spruce:spruce-android:1.0.2.
         > Could not parse POM https://jcenter.bintray.com/com/willowtreeapps/spruce/spruce-android/1.0.2/spruce-android-1.0.2.pom
            > project must be the root tag
```

**Comment by bret-fears** [comment]
Hi there. Thank you for reporting this. We're also noticing the same locally. We're trying to get in touch with bintray support as this appears to be a linking issue. For the time being you may downgrade to version 1.0.1 while we try to resolve this issue. Thank you!

**Comment by bret-fears** [comment]
@amanzan apologies for the delay. In order to use the latest 1.0.2 version with the new publishing rules you'll need to also add the maven repository to your root gradle configuration by adding the following:

    repositories {
        maven {
            url  "https://dl.bintray.com/bfears/maven"
        }
    }

Please reach out if you run into any other issues. Thank you.

**Comment by amanzan** [comment]
Hi @bret-fears , still getting "Unresolved reference" in SpruceBuilder for version 1.0.2
Version 1.0.1 seems to work

**Comment by bret-fears** [comment]
Hi @amanzan did you also add the maven repository reference to your gradle configuration? With the latest version the linking behavior has changed requiring it to be added in order to resolve the latest.

**Comment by amanzan** [comment]
Yes, I added maven repo to the root build.gradle, and 
```implementation 'com.willowtreeapps.spruce:spruce-android:1.0.2'```
to app's build.gradle

**Comment by bret-fears** [comment]
@amanzan Thank you for confirming. I have re-opened this issue and I will work on a solution and I will add additional information here once it's known.

**Comment by bret-fears** [comment]
@amanzan For solidarity on the issue can you please follow these instructions https://www.jetbrains.com/help/idea/invalidate-caches.html and re-fetch gradle dependencies then report back? Thanks!

**Comment by amanzan** [comment]
Done, and still same issue. For some reason it's not finding Spruce classes...

**Comment by bret-fears** [comment]
Okay thanks for the information

**Comment by bret-fears** [comment]
So far I've been unable to recreate the "unresolved reference" issue. I created a brand new project, added the repository and the implementation for version 1.0.2, it successfully builds and I'm able to reference Spruce classes. Would you be willing to share any more details around your setup?

**Comment by amanzan** [comment]
@bret-fears just tested again, and it was my bad: I was adding the maven repository inside buildscript - repositories instead of adding it inside allprojects - repositories. Now I'm able to reference Spruce classes, thanks and sorry for the hassle!

**Comment by bret-fears** [comment]
@amanzan Oh this is wonderful news. I'm so relieved that you're able to resolve the library now. Thank you for following up on this and closing the issue. Please feel free to reach out with any other issues or questions. I hope you have a wonderful weekend.
