### ISSUE TITLE
Create a new version

### ISSUE THREAD

**Issue by filol** [willowtreeapps/spruce-android#88]
Could you create a new release version from the updated master branch for that change of issue #81 is available as gradle dependency?

**Comment by karadkar** [comment]
that would be really helpfull

**Comment by bret-fears** [comment]
Bugfix version 1.0.1 has been tagged and created in bintray. You may reference 1.0.1 within gradle to take advantage of this #81 bugfix 

> compile 'com.willowtreeapps.spruce:spruce-android:1.0.1'

**Comment by filol** [comment]
Thanks!

**Comment by bret-fears** [comment]
My pleasure! Thank you for all of your help and support. Enjoy the new release.
