### ISSUE TITLE
RecyclerActivity finally several items no animation

### ISSUE THREAD

**Issue by qaz349293703** [willowtreeapps/spruce-android#93]
when i open the RecyclerActivity , and scroll the end， onclick the item， they do not have animation。only the index for  0-5 items have animation

**Comment by bret-fears** [comment]
Thank you, qaz349293703, you're correct. Only the initial on screen items are being animated. I'll make a fix for that and explain the situation in code on this ticket.

**Comment by bret-fears** [comment]
https://github.com/willowtreeapps/spruce-android/pull/97 with commit bb0dfc9 fixes the issue. Note: Re-calling start() through initSpruce()
